services:
  buergerbot:
    container_name: buergerbot
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/gwauge/buergerbot:latest # GitHub Container Registry image
    # image: buergerbot:latest # Docker Hub image
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./config.yaml:/app/config.yaml
