name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
    tags: ["*"] # triggers on new tags

env:
  IMAGE_NAME: buergerbot

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # use commit hash as the tag for non-tag builds
      - name: Determine Image Tag
        id: vars
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
            echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

      # All builds: x86-64 only, using commit hash as the tag
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.IMAGE_TAG }}

      # Tag builds: multi-arch for AMD64 and ARM64, plus 'latest' tag
      - name: Set up QEMU (latest)
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/setup-qemu-action@v2

      - name: Build and Push (latest)
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
